language: python
python:
  - "3.7"
  - "3.8"
  - "3.8-dev"  # 3.8 development branch
  - "nightly"  # nightly build
install:
  - pip install -r test-requirements.txt
script:
    # - python -m pytest
  - python3.7 -m pytest --cov-report term --cov=anyencoder
